#!/bin/bash

# @see Following atrias:1ec359e:patches_etc/sudo_ros
# @see http://superuser.com/a/422962/284846

# @todo How to trim down LD_LIBRARY_PATH to only ROS stuff?

secure_path="/opt/ros/hydro/bin:/opt/ros/hydro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
env_keep="PYTHONPATH ROS_MASTER_URI"

sudo PATH="$secure_path" PYTHONPATH="$PYTHONPATH" ROS_MASTER_URI="$ROS_MASTER_URI" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" ROS_PACKAGE_PATH="$ROS_PACKAGE_PATH" "$@"
